Name:		opal
Summary:	Open Phone Abstraction Library
Version:	3.6.6
Release:	4%{?dist}.goose.1
URL:		http://www.opalvoip.org/
# We cannot use unmodified upstream source code because it contains the 
# non-free iLBC codec.
# rm -rf plugins/audio/iLBC/
# rm -rf src/codec/iLBCmf.cxx
#Source0:	ftp://ftp.gnome.org/pub/gnome/sources/%{name}/3.6/%{name}-%{version}.tar.bz2
Source0:	%{name}-%{version}-noilbc.tar.bz2
Patch0:		opal-3.6.1-noilbc.patch
# Fix strict aliasing errors on big endian machines
Patch1:         opal-3.6.6-strict-aliasing.patch
# Fix multilib conflicts for buildopts.h autogenerated file
Patch2:         opal-3.6.6-buildopts.patch
Patch3:         opal-3.6.6-multilib-661769.patch

License:	MPLv1.0
Group:		System Environment/Libraries
BuildRequires:	ptlib-devel = 2.6.5
BuildRequires:	openldap-devel
BuildRequires:	openssl-devel
BuildRequires:	libtheora-devel
BuildRequires:	speex-devel
BuildRequires:	SDL-devel
BuildRequires:	expat-devel

BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
Open Phone Abstraction Library, implementation of the ITU H.323
teleconferencing protocol, and successor of the openh323 library.

%package devel
Summary:	Development package for opal
Group:		Development/Libraries
Requires:	opal = %{version}-%{release}
Requires:	openssl-devel
Requires:	ptlib-devel = 2.6.5
Requires:	pkgconfig

%description devel
The opal-devel package includes the development libraries and 
header files for opal.

%prep
%setup -q 
%patch0 -p1 -b .noilbc
%patch1 -p1 -b .strict-alias
%patch2 -p1 -b .buildopts
%patch3 -p1 -b .multilib 

%build
%configure

make OPTCCFLAGS="$RPM_OPT_FLAGS" %{?_smp_mflags} V=1

%install
rm -rf $RPM_BUILD_ROOT

make DESTDIR=$RPM_BUILD_ROOT install

rm -f $RPM_BUILD_ROOT/%{_datadir}/opal/opal_inc.mak
rm -f $RPM_BUILD_ROOT/%{_libdir}/libopal_s.a

%clean
rm -rf $RPM_BUILD_ROOT

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc mpl-1.0.htm
%{_libdir}/*.so.*
%{_libdir}/%{name}-%{version}

%files devel
%defattr(-,root,root,-)
%doc docs/*
%{_includedir}/*
%{_libdir}/*.so
%{_libdir}/pkgconfig/opal.pc

%changelog
* Wed Mar 7 2012 Clint Savage <clints@gooseproject.org> - 3.6.6-4.goose.1
- Add another patch to make multilib work

* Mon Jun 21 2010 Benjamin Otte <otte@redhat.com> - 3.6.6-4
- Add another patch to make multilib work
Resolves: rhbz#605094

* Mon Jun 21 2010 Benjamin Otte <otte@redhat.com> - 3.6.6-2
- Add patch to make multilib work
- Fix strict aliasing errors
Resolves: rhbz#605094

* Tue Sep 22 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.6-1
- New 3.6.6 stable release

* Fri Aug 21 2009 Tomas Mraz <tmraz@redhat.com> - 3.6.4-4
- rebuilt with new openssl

* Sat Jul 25 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 3.6.4-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_12_Mass_Rebuild

* Mon Jul  6 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.4-2
- Increment required ptlib version

* Mon Jul  6 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.4-1
- New 3.6.4 stable release

* Thu May 28 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.2-2
- Add an upstream patch to fix a deadlock issue.

* Tue May 19 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.2-1
- New stable release for ekiga 3.2.1

* Sun Apr 26 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.1-3
- pull in some upstream fixes for possible crashes

* Tue Apr 21 2009 Tom "spot" Callaway <tcallawa@redhat.com> - 3.6.1-2
- pull out ilbc codec due to legal issues

* Wed Mar 18 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.1-1
- New stable release for ekiga 3.2.0

* Fri Mar  6 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.0-2
- Remove CELT until the bitstream is stable and can hence intercommunicate between versions

* Tue Mar  3 2009 Peter Robinson <pbrobinson@gmail.com> - 3.6.0-1
- New release for ekiga 3.1.2 beta

* Thu Feb 26 2009 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 3.5.2-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_11_Mass_Rebuild

* Mon Feb 10 2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-7
- Add patches to fix gcc44 compilation, remove celt until issues
  are fixed upstream

* Tue Feb 3  2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-6
- Add support for the celt codec

* Mon Feb 2  2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-5
- Fix blank soname 

* Sat Jan 17 2009 Tomas Mraz <tmraz@redhat.com> - 3.5.2-4
- rebuild with new openssl

* Tue Jan 13 2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-3
- Yet another dep that configure doesn't check and it just fails on

* Tue Jan 13 2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-2
- Add a build dep

* Tue Jan  6 2009 Peter Robinson <pbrobinson@gmail.com> - 3.5.2-1
- New release for ekiga 3.1.0 beta
- Some updates from merge review

* Fri Dec  5 2008 Peter Robinson <pbrobinson@gmail.com> - 3.4.2-2
- Update spec to ensure we own directories

* Mon Oct 20 2008 Peter Robinson <pbrobinson@gmail.com> - 3.4.2-1
- Update to new stable release for ekiga 3.0.1

* Tue Sep 23 2008 Peter Robinson <pbrobinson@gmail.com> - 3.4.1-1
- Update to new stable release for ekiga 3

* Thu Sep 11 2008 Peter Robinson <pbrobinson@gmail.com> - 3.3.1-1
- Update release to 3.3.1 for ekiga 3 beta

* Mon Aug 11 2008 Tom "spot" Callaway <tcallawa@redhat.com> - 2.2.11-5
- fix license tag

* Mon May 12 2008 Paul W. Frields <stickster@gmail.com> - 2.2.11-4
- Rebuild in service of ekiga (#441202)

* Wed Feb 20 2008 Fedora Release Engineering <rel-eng@fedoraproject.org> - 2.2.11-3
- Autorebuild for GCC 4.3

* Thu Dec  6 2007 Jeremy Katz <katzj@redhat.com> - 2.2.11-2
- rebuild for new openssl and openldap

* Tue Sep 18 2007 Daniel Veillard <veillard@redhat.com> - 2.2.11-1
- upstream release of 2.2.11

* Tue Sep 18 2007 Daniel Veillard <veillard@redhat.com> - 2.2.10-1
- upstream release of 2.2.10
- includes the 2 cisco patches

* Wed Aug 22 2007 Daniel Veillard <veillard@redhat.com> - 2.2.8-5.fc8
- added 2 patches needed when using a CISCO server

* Sun Apr 15 2007 Daniel Veillard <veillard@redhat.com> - 2.2.8-1
- upstream release of 2.2.8

* Mon Mar 12 2007 Daniel Veillard <veillard@redhat.com> - 2.2.6-1
- upstream release of 2.2.6

* Wed Feb 14 2007 Daniel Veillard <veillard@redhat.com> - 2.2.5-1
- upstream release of 2.2.5

* Mon Jan 22 2007 Daniel Veillard <veillard@redhat.com> - 2.2.4-1
- upstream release of 2.2.4

* Wed Dec 20 2006 Daniel Veillard <veillard@redhat.com> - 2.2.3-4
- applied patch from upstream to fix RFC2833 DTMF duration problem
- Resolves: rhbz#220333

* Mon Nov  6 2006 Daniel Veillard <veillard@redhat.com> - 2.2.3-3
- moved the .so to -devel
- Resolves: rhbz#203633

* Sat Oct 21 2006 Matthias Clasen <mclasen@redhat.com> - 2.2.3-2
- Rebuild against newer pwlib

* Sat Oct 21 2006 Matthias Clasen <mclasen@redhat.com> - 2.2.3-1
- Update to 2.2.3

* Wed Jul 12 2006 Jesse Keating <jkeating@redhat.com> - 2.2.2-1.1
- rebuild

* Wed May 31 2006 Daniel Veillard <veillard@redhat.com> - 2.2.2-1
- new release for ekiga-2.0.2
- try to fix #192740 mutilib problem

* Tue Mar 14 2006 Daniel Veillard <veillard@redhat.com> - 2.2.1-1
- last minute break fix and new release

* Tue Mar 14 2006 Ray Strode <rstrode@redhat.com> - 2.2.0-2
- rebuild

* Mon Mar 13 2006 Daniel Veillard <veillard@redhat.com> - 2.2.0-1
- final version for ekiga-2.0.0

* Mon Feb 13 2006 Daniel Veillard <veillard@redhat.com> - 2.1.3-1
- new beta version for ekiga

* Fri Feb 10 2006 Jesse Keating <jkeating@redhat.com> - 2.1-1.2
- bump again for double-long bug on ppc(64)

* Tue Feb 07 2006 Jesse Keating <jkeating@redhat.com> - 2.1-1.1
- rebuilt for new gcc4.1 snapshot and glibc changes

* Tue Jan 24 2006 Daniel Veillard <veillard@redhat.com> - 2.1-1
- initial version based on the openh323 spec file
